*feature: Search through recent projects to find repository path

diff --git a/zcm-feature b/zcm-feature
--- a/zcm-feature
+++ b/zcm-feature
@@ -640,10 +640,44 @@ if (( list + create + create_from_commits + add + delete + delete_feature + set_
     entries=( "${(@f)"$(<$feature_file)"}" )
 
     local project_line="${ZCMDR[current_project]}"
+    local root_dir="${ZCMDR[current_repo]}"
 
     if [[ "${entries[2]}" != "$project_line" ]]; then
-        print "Warning: editing not current project ${entries[2]:t:r}"
+        print "${fg_bold[red]}Warning: editing not current project \`${entries[2]:t:r}'${reset_color}"
         project_line="${entries[2]}"
+
+        # Search through recently used projects
+        # to find the path to repository
+
+        local -a all_circular_paths last_entries
+        local p found="no"
+
+        __zcmdr_stdlib_circular_paths "last_project"
+        all_circular_paths=( "${reply[@]}" )
+
+        for p in "${all_circular_paths[@]}"; do
+            last_entries=( "${(@f)"$(<$p)"}" )
+            if [[ "${last_entries[1]}" = "$project_line" ]]; then
+                root_dir="${last_entries[2]}"
+                found="yes"
+                break
+            fi
+        done
+
+        if [[ "$found" = "no" ]]; then
+            print "Could not find repository of project \`${entries[2]:t:r}\' because"
+            print "the project is not remembered in recent-projects database."
+            print "Cannot use feature's commits, will only open feature's files."
+            print "Proceed? [y/n]"
+            local answer="n"
+            read -qs answer
+            if [[ "$answer" = "n" ]]; then
+                echo "Aborting."
+                return 22
+            fi
+
+            root_dir=""
+        fi
     fi
 
     #
@@ -676,11 +710,11 @@ if (( list + create + create_from_commits + add + delete + delete_feature + set_
     commits=( "${(Q)commits[@]}" )
 
     if [[ -n "${commits[1]}" ]]; then
-        local root_dir="${ZCMDR[current_repo]}"
         local -aU save_files
-
-        if [[ ! -d "$root_dir" || ( ! -d "$root_dir"/.git && ! -d "$root_dir"/.hg ) ]]; then
-            print "Warning: feature has commits but project's dir isn't a Git nor Hg repository"
+        if [[ -z "$root_dir" || ! -d "$root_dir" || ( ! -d "$root_dir"/.git && ! -d "$root_dir"/.hg ) ]]; then
+            if [[ -n "$root_dir" ]]; then
+                print "${fg_bold[red]}Warning: feature has commits but project's dir isn't a Git nor Hg repository${reset_color}"
+            fi
         else
             local cmt
             local -a files2
